<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java" nsURI="ecore://nasdanika.org/models/java" nsPrefix="org.nasdanika.models.java">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="A model of Java language - modules, packages, classes, compilation units, methods, statements, ..."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ImportManager" instanceTypeName="java.util.function.Function&lt;String, String>"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Merger" instanceTypeName="java.util.function.BiFunction&lt;String, String, String>"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigestPredicate" instanceTypeName="java.util.function.Predicate&lt;org.eclipse.emf.ecore.EObject>"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//Marked">
    <eOperations name="update" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Calls update on children and then updates source code using children source code. Returns updated source code. "/>
      </eAnnotations>
      <eParameters name="importManager" eType="#//ImportManager"/>
    </eOperations>
    <eOperations name="digest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Computes digest to be used by generators to detect manual changes"/>
      </eAnnotations>
      <eParameters name="predicate" eType="#//DigestPredicate">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Predicate allows to exclude model element for digest computation, e.g. Generated annotation"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Source" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" eSuperTypes="#//Source">
    <eOperations name="merge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Merges new source code with the current code preserving manual changes in the current code"/>
      </eAnnotations>
      <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Source code to merge with the current code"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="merger" eType="#//Merger"/>
    </eOperations>
    <eOperations name="merge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Collects  new source code from children and merges with the current code preserving manual changes in the current code"/>
      </eAnnotations>
      <eParameters name="merger" eType="#//Merger"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" abstract="true" eSuperTypes="#//Source">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//Comment"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationMember" eSuperTypes="#//Member"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constructor" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumConstant" eSuperTypes="#//Member"/>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//Member"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//Source"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Code" abstract="true" eSuperTypes="#//Member"/>
  <eClassifiers xsi:type="ecore:EClass" name="Initializer" eSuperTypes="#//Code"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassInitializer" eSuperTypes="#//Code"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//Code"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//Marked">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//Type"/>
</ecore:EPackage>
