<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="java" nsURI="ecore://nasdanika.org/models/java" nsPrefix="org.nasdanika.models.java">
  <eClassifiers xsi:type="ecore:EClass" name="ImportManager" instanceTypeName="java.util.function.Function&lt;String, String>"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Merger" instanceTypeName="java.util.function.BiFunction&lt;String, String, String>"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DigestPredicate" instanceTypeName="java.util.function.Predicate&lt;org.eclipse.emf.ecore.EObject>"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//Marked">
    <eTypeParameters name="C">
      <eBounds eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eTypeParameters>
    <eOperations name="update" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Calls update on children and then updates source code using children source code. Returns updated source code. "/>
      </eAnnotations>
      <eParameters name="importManager" eType="#//ImportManager"/>
    </eOperations>
    <eOperations name="digest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Computes digest to be used by generators to detect manual changes"/>
      </eAnnotations>
      <eParameters name="predicate" eType="#//DigestPredicate">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Predicate allows to exclude model element for digest computation, e.g. Generated annotation"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Source">
        <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverage">
      <eGenericType eTypeParameter="#//Source/C"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit">
    <eOperations name="merge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Merges new source code with the current code preserving manual changes in the current code"/>
      </eAnnotations>
      <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Source code to merge with the current code"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="merger" eType="#//Merger"/>
    </eOperations>
    <eOperations name="merge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Collects  new source code from children and merges with the current code preserving manual changes in the current code"/>
      </eAnnotations>
      <eParameters name="merger" eType="#//Merger"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imports" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//Source">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//SourceFileCoverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eTypeParameters name="C">
      <eBounds eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Simple (short) name. E.g. Map"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullyQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Fully qualified name where applicable. E.g. java.util.Map"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" eOpposite="#//Reference/target"/>
    <eGenericSuperTypes eClassifier="#//Source">
      <eTypeArguments eTypeParameter="#//NamedElement/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" abstract="true">
    <eTypeParameters name="C">
      <eBounds eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//Comment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedTypes" upperBound="-1"
        eType="#//GenericType" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="All types referenced by this member including types refernced from code"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" eType="#//Annotation"/>
    <eGenericSuperTypes eClassifier="#//NamedElement">
      <eTypeArguments eTypeParameter="#//Member/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eOpposite="#//NamedElement/references">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Referenced named element"/>
      </eAnnotations>
      <eGenericType eClassifier="#//NamedElement">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//NamedElement">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericType" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1"
        eType="#//GenericType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerBound" eType="#//GenericType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" eType="#//GenericType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//Reference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//NamedElement">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bounds" upperBound="-1"
        eType="#//GenericType"/>
    <eGenericSuperTypes eClassifier="#//NamedElement">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement">
    <eTypeParameters name="C">
      <eBounds eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//GenericType"
        containment="true"/>
    <eGenericSuperTypes eClassifier="#//NamedElement">
      <eTypeArguments eTypeParameter="#//TypedElement/C"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Member">
        <eTypeArguments>
          <eUpperBound eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supertypes" upperBound="-1"
        eType="#//GenericType" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For classes the first element is the superclass and the rest are implemented interfaces"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
        eType="#//TypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permits" upperBound="-1"
        eType="#//GenericType" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For classes the first element is the superclass and the rest are implemented interfaces"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Member">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//ClassCoverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationInterface" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationInterfaceMember">
    <eGenericSuperTypes eClassifier="#//Member">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constructor" eSuperTypes="#//Operation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enum" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumConstant">
    <eGenericSuperTypes eClassifier="#//Member">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" eType="#//Field"
        eOpposite="#//Field/accesses">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Fully qualified field name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reads" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accesses" eType="#//FieldAccess"
        eOpposite="#//FieldAccess/field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" eType="#//Code"
        containment="true"/>
    <eGenericSuperTypes eClassifier="#//Member">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//TypedElement">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
    <eGenericSuperTypes eClassifier="#//Source">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//ModuleCoverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//Source">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//PackageCoverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="overrides" eType="#//Method"
        eOpposite="#//Method/overriddenBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overriddenBy" upperBound="-1"
        eType="#//Method" eOpposite="#//Method/overrides"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Code">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fieldAccesses" upperBound="-1"
        eType="#//FieldAccess" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingCalls" upperBound="-1"
        eType="#//Call" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" containment="true">
      <eGenericType eClassifier="#//Source">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Member">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//MethodCoverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initializer" eSuperTypes="#//Code"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassInitializer" eSuperTypes="#//Code"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varArg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifiers" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//TypedElement">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//Coverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiverParameter" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exceptions" upperBound="-1"
        eType="#//GenericType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1"
        eType="#//TypeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingCalls" eType="#//Call"
        eOpposite="#//Call/operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//Code"/>
    <eGenericSuperTypes eClassifier="#//TypedElement">
      <eTypeArguments eClassifier="ecore:EClass ../../org.nasdanika.models.coverage/model/coverage.ecore#//MethodCoverage"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//Operation"
        eOpposite="#//Operation/incomingCalls"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//Type"/>
</ecore:EPackage>
